### ISSUE TITLE
Reprint your plugin to MCBBS

### ISSUE THREAD

**Issue by xieyiyangshadow** [Markiesch/EpicReplant#3]
Hi, I'm a chinese minecraft player. I want to reprint your plugin which called Epic Replant to a chinese minecraft communicating website called MCBBS(www.mcbbs.net). I will transform the overview of the plugin and sign the download link on spigot. Tell me if it's OK. Thanks!

**Comment by Markiesch** [comment]
> Hi, I'm a chinese minecraft player. I want to reprint your plugin which called Epic Replant to a chinese minecraft communicating website called MCBBS([www.mcbbs.net](http://www.mcbbs.net)). I will transform the overview of the plugin and sign the download link on spigot. Tell me if it's OK. Thanks!

Hi @xieyiyangshadow,

Thanks for opening this issue. Good to hear there is interest in Epic Replant and I would love you to forward my plugin to mcbbs. If you can link the official spigot page as download link would be awesome! I would also like you to share the mcbbs link when you published there.

- Markiesch

**Comment by xieyiyangshadow** [comment]
That's great! I'll let you know as soon as I post it.

**Comment by xieyiyangshadow** [comment]
https://www.mcbbs.net/thread-1311157-1-1.html , Here's the link!
