### ISSUE TITLE
OfflineGrowth Support

### ISSUE THREAD

**Issue by kingsushi001** [Markiesch/EpicReplant#4]
Hi

Is there any chance you could add support for OfflineGrowth?
[https://www.spigotmc.org/resources/offlinegrowth-plants-grow-on-unloaded-chunks-1-8x-1-19x.87615/](url)

I see there is an API section on the plugin's page.

**Comment by markschuurmans** [comment]
Hey, Thanks for the idea! I implemented this, and the feuture is available in the next [EpicReplant release (1.8.0)](https://www.spigotmc.org/resources/epic-replant.95096/update?update=481868)

**Comment by kingsushi001** [comment]
Thank you so much. Lol, I updated 4mins after you updated it on spigot. It's working great.
